export interface QB
{
    id: String,
    name: String,
    team: String,
    position: String,
    avgPts: Number,
    fGrade: Number,
    oGrade: Number,
    passTDs: Number,
    rushTDs: Number,
    passYDs: Number,
    rushYDs: Number,
    interceptions: Number,
    fumbles: Number,
    athleticism: Number, 
    agility: Number, 
    strength: Number, 
    speed: Number, 
    productivity: Number, 
    armStrength: Number, 
    accuracy: Number, 
    decisionMaking: Number, 
    dualThreat: Number, 
    bigPlay: Number, 
  }