export interface RB
{
    id: String,
    name: String,
    team: String,
    position: String,
    avgPts: Number,
    fGrade: Number,
    oGrade: Number,
    totalTDs: Number,
    totalYDs: Number,
    carries: Number,
    receptions: Number,
    fumbles: Number,
    athleticism: Number,
    agility: Number,
    strength: Number,
    speed: Number,
    productivity: Number,
    vision: Number,
    breakTackle: Number,
    ballSecurity: Number,
    catching: Number,
    dualThreat: Number,
    bigPlay: Number,
  }