export interface WR 
{
    id: String,
    name: String,
    team: String,
    position: String,
    avgPts: Number,
    fGrade: Number,
    oGrade: Number,
    totalTDs: Number,
    totalYDs: Number,
    receptions: Number,
    fumbles: Number,
    athleticism: Number,
    agility: Number,
    strength: Number,
    speed: Number,
    productivity: Number,
    catching: Number,
    routeRunning: Number,
    runAfterCatch: Number,
    deepThreat: Number,
    bigPlay: Number,
  }
